stages:
  - build_and_test

frontend:test:
  stage: build_and_test
  image: node:20-alpine
  tags:
    - Podman
    - CREMI
  before_script:
    - apk add --no-cache chromium su-exec
    - export CHROME_BIN=/usr/bin/chromium-browser
    - export CHROME_FLAGS="--headless --no-sandbox --disable-gpu --disable-dev-shm-usage"
  script:
    - cd frontend
    - npm install
    - su-exec node ./node_modules/.bin/ng test --watch=false --browsers=ChromeHeadless
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend
    paths:
      - frontend/node_modules/

backend:test:
  stage: build_and_test
  image: node:20-alpine
  tags:
    - Podman
    - CREMI
  script:
    - cd backend
    - npm install
    - npm test
  cache:
    key: ${CI_COMMIT_REF_SLUG}-backend
    paths:
      - backend/node_modules/
